car

In [6]:
import random, csv
headers = ['id', 'pos', 'time']
rows = []
for i in range(100):
    d = {}
    d['time'] = 0
    d['pos'] = random.randint(0, 42402)
    d['id'] = i
    rows.append(d)

In [7]:
with open('data/car.csv', 'w') as f:
    f_csv = csv.DictWriter(f, headers)
    f_csv.writeheader()
    f_csv.writerows(rows)

pass

In [8]:
import random, csv
headers = ['id', 'bgn', 'end', 'time']
rows = []
for i in range(100):
    d = {}
    d['end'] = random.randint(0, 42402)
    d['time'] = random.randint(0, 86400)
    d['bgn'] = random.randint(0, 42402)
    d['id'] = i
    rows.append(d)

In [9]:
with open('data/order.csv', 'w') as f:
    f_csv = csv.DictWriter(f, headers)
    f_csv.writeheader()
    f_csv.writerows(rows)

In [48]:
from pickle import load
input = open('data/pos_data', 'rb')
pos_list = load(input)
input.close()
print(pos_list[4371])

(4371, (104.0516678, 30.7000894))

In [46]:
goal = pd.read_csv("/Users/zhehaoyu/Desktop/MCM/模考/D/代码/output.csv")

In [22]:
from geopy.distance import geodesic

def dist (lon1, lat1, lon2, lat2):
    return geodesic((lat1,lon1),(lat2,lon2)).m

In [40]:
maps = []
for i in range(goal.shape[0]):
    lat = goal['lat'][i]
    lon = goal['lon'][i]
    dis = []
    for pos in pos_list:
        temp = geodesic((lat,lon),(pos[1][1],pos[1][0])).m
        dis.append(temp)
    maps.append(dis.index(min(dis)))

In [49]:
m = pd.DataFrame(maps)
goal['index'] = m
goal.to_csv("position2index.csv",index=False,sep=',')

In [50]:
goal

           lon        lat   cnt  index
0   104.074890  30.665570  3551  13951
1   104.089270  30.650850  2543  24887
2   104.066200  30.684440  2472  25229
3   104.087080  30.682100  2138  25912
4   104.105324  30.663950  2098   6456
5   104.043860  30.682320  1805  25402
6   104.061520  30.642740  1505  37248
7   104.051930  30.700400  1485   4371
8   104.040627  30.662699  1474  13059
9   104.073181  30.702131  1470   6104
10  104.119460  30.679890  1261  20129
11  104.104421  30.695113  1186  14958
12  104.027790  30.695670   934  40862
13  104.042790  30.717170   851  40789
14  104.121926  30.650748   745  41147
15  104.106905  30.637895   703   7822
16  104.100320  30.717220   638  25794
17  104.019240  30.667720   526  28525
18  104.024610  30.648170   486  10500
19  104.075040  30.723560   460  30559
20  104.047320  30.627060   457  28051
21  104.090850  30.620860   420  25911
22  104.144240  30.672820   333  21448
23  104.000170  30.676930   326  21307
24  104.052100  30.733590   307  22218
25  104.070871  30.609781   305  18229
26  104.125430  30.705870   302  35110
27  104.025100  30.630030   294  36367
28  104.051500  30.766300   290  29426
29  104.013360  30.717440   274  33660
..         ...        ...   ...    ...
59  104.166400  30.716830    66  32465
60  104.117340  30.744500    65  22283
61  104.179750  30.649580    60  16266
62  103.951230  30.664400    59  22339
63  104.186570  30.686900    56  27793
64  104.066940  30.543080    54  24138
65  104.048920  30.785830    54  27897
66  103.964280  30.691560    53  37423
67  103.971137  30.758578    51    250
68  103.994350  30.736990    51  28325
69  103.976820  30.576990    48  20986
70  104.144810  30.713420    48  29206
71  104.146370  30.732690    46  29200
72  104.109741  30.590190    46  20631
73  103.971099  30.740532    46  39607
74  104.036230  30.578170    45  25433
75  104.000370  30.601520    43  39276
76  104.003310  30.570320    41  29927
77  104.096730  30.551120    39  38919
78  104.137300  30.585470    39   7516
79  104.036360  30.557410    38   5270
80  104.185730  30.667395    37  42333
81  103.996810  30.755880    36  20664
82  104.162730  30.597120    36  21463
83  104.138110  30.792841    36   1137
84  104.058428  30.802345    35  31446
85  104.078050  30.810120    34   6946
86  104.020100  30.592551    33  40017
87  104.159790  30.802950    30  15658
88  104.142230  30.760020    30  29896

[89 rows x 4 columns]

## generate

In [10]:
import pandas as pd

In [11]:
spc = pd.read_csv("/Users/zhehaoyu/Desktop/MCM/模考/D/代码/zsj_algorithm_0.1.0/data/car.csv")

In [12]:
spc

    id    pos  time
0    0  41549     0
1    1   6413     0
2    2   5728     0
3    3  13907     0
4    4  33342     0
5    5  29739     0
6    6  18151     0
7    7  21667     0
8    8   9126     0
9    9   7858     0
10  10  11147     0
11  11  11086     0
12  12  23366     0
13  13  19391     0
14  14  15995     0
15  15  31078     0
16  16  30872     0
17  17  27294     0
18  18  27336     0
19  19   3468     0
20  20  38780     0
21  21   5435     0
22  22   1552     0
23  23  30455     0
24  24    730     0
25  25   3986     0
26  26  42277     0
27  27   5844     0
28  28  21967     0
29  29  33503     0
..  ..    ...   ...
70  70  23389     0
71  71  30145     0
72  72  38864     0
73  73  20274     0
74  74   9318     0
75  75   7948     0
76  76  29774     0
77  77   8099     0
78  78  27277     0
79  79  41774     0
80  80   3321     0
81  81  26751     0
82  82  32331     0
83  83  12606     0
84  84   1252     0
85  85  10134     0
86  86   4887     0
87  87   8198     0
88  88   2717     0
89  89  10007     0
90  90  33780     0
91  91  40518     0
92  92  19288     0
93  93  40044     0
94  94  11610     0
95  95  35147     0
96  96  20894     0
97  97   9540     0
98  98  13829     0
99  99  26571     0

[100 rows x 3 columns]

In [13]:
spo = pd.read_csv("/Users/zhehaoyu/Desktop/MCM/模考/D/代码/zsj_algorithm_0.1.0/data/order.csv")

In [14]:
spo

    id    bgn    end   time
0    0  41413   3868  70243
1    1   3330  19343  67270
2    2  19894    431  60235
3    3  37609  14888  33012
4    4  27698    681  20750
5    5  27947  27850    371
6    6   3731  19830   9175
7    7  15444   8465  48187
8    8  29470  31668  62513
9    9  32113  33824  42833
10  10   1730   4475  53898
11  11  34922  16099  29204
12  12  36721  21358  35727
13  13   7516  18231  10305
14  14  20969  16567  36478
15  15  24356  24656  45512
16  16  12511   8376   7880
17  17  13042  34108  34080
18  18  33992   8606  65205
19  19  35010  37136  76854
20  20  19973  39187  50590
21  21  11348  27895  59063
22  22  40793  31434  63483
23  23  34331  22691  33409
24  24  27259  38071   3027
25  25  12107  39300   5366
26  26  41623  39115  30519
27  27  19014  29547  76839
28  28  33684  27162  30969
29  29  23228  29016   9795
..  ..    ...    ...    ...
70  70  39916  24487  36147
71  71  29267  11364   7629
72  72  37526  18434  64399
73  73  38747  21698  85262
74  74   4481  18352  25798
75  75  31434  22269  74521
76  76  35585   1251  23089
77  77  33153  28706  69859
78  78   1089  17744  15117
79  79  27425  12123  75405
80  80  19057  25203  36621
81  81  41444   3767  83764
82  82  36044   9636  55376
83  83  34026  10534  79319
84  84  31706  24620  55425
85  85  21924  14040  49014
86  86  35663  21748  41116
87  87  35695  42119  24283
88  88  40100  26808  77931
89  89  18888  36021  58210
90  90   9076  21966  77681
91  91  41471  20462  52193
92  92  18459   8603  33923
93  93  18708  37817  34960
94  94  35725  21115  69671
95  95  26546  33013  78318
96  96  35108  14954   6090
97  97  33122   9691  64997
98  98  29715   8769  79074
99  99  21774   6851  31287

[100 rows x 4 columns]

In [13]:
li = [1,2,2,2,34,4,554,5,35,5]
result=[li.index(x) for x in li if x >5]
print(result)

[4, 6, 8]