In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
# 统计方差
df = pd.read_csv('/Users/zhehaoyu/Desktop/MCM/D题/codes/match_indicator.csv')
cent = pd.read_csv('/Users/zhehaoyu/Desktop/MCM/D题/codes/match_indicator_individual.csv')
passes =  pd.read_csv('/Users/zhehaoyu/Desktop/MCM/D题/codes/pass_data_in_each_game.csv')
df = df.sort_values(['teamID', 'matchID'])
df

,matchID,teamID,avg_clustering,total_degree,clique_number,avg_position_x,avg_position_y
0,1,Huskies,0.110728,369,8,50.112622,52.196929
2,2,Huskies,0.137660,180,7,42.825383,52.847287
4,3,Huskies,0.138964,324,8,48.107242,51.107686
6,4,Huskies,0.132631,354,9,47.862234,49.898077
8,5,Huskies,0.138370,382,9,45.981208,51.832945
10,6,Huskies,0.096407,318,7,54.912946,54.876030
12,7,Huskies,0.144553,384,8,54.956211,50.252278
14,8,Huskies,0.136283,295,9,42.292793,49.109075
16,9,Huskies,0.144408,168,7,47.830933,54.783346
18,10,Huskies,0.166429,359,7,55.463600,51.499557
20,11,Huskies,0.153766,183,8,50.929014,49.383821
22,12,Huskies,0.138634,132,7,47.024015,49.127337
24,13,Huskies,0.154970,247,7,47.612626,48.197297
26,14,Huskies,0.151775,347,8,46.650566,47.580208
28,15,Huskies,0.228421,271,7,49.047317,56.542170
30,16,Huskies,0.113296,80,5,41.892338,51.601801
32,17,Huskies,0.137599,304,7,44.398526,50.368889
34,18,Huskies,0.201136,312,8,48.424650,48.110037
36,19,Huskies,0.155763,248,7,46.470811,51.551413
38,20,Huskies,0.129709,230,7,53.956536,48.977575
40,21,Huskies,0.194520,366,8,48.289016,46.004725
42,22,Huskies,0.128754,239,8,51.528678,50.316731
44,23,Huskies,0.120514,236,7,46.143302,52.017265
46,24,Huskies,0.170113,320,8,51.674641,46.797577
48,25,Huskies,0.188588,249,9,49.632969,52.749410
50,26,Huskies,0.144414,287,9,53.129705,50.320357
52,27,Huskies,0.118014,283,9,50.392322,56.565088
54,28,Huskies,0.173802,238,7,50.029161,51.391574
56,29,Huskies,0.160238,220,9,46.153547,40.879690
58,30,Huskies,0.160967,312,7,54.318040,56.519376
...,...,...,...,...,...,...,...
25,13,Opponent13,0.155908,504,8,49.706365,49.280491
73,37,Opponent13,0.182992,246,7,49.279181,50.197030
27,14,Opponent14,0.114266,347,7,51.889141,56.674271
75,38,Opponent14,0.179708,355,8,49.471117,47.623325
29,15,Opponent15,0.189601,224,7,51.904366,49.798888
71,36,Opponent15,0.175041,298,9,51.028769,48.359037
31,16,Opponent16,0.104596,605,8,55.943540,49.756448
65,33,Opponent16,0.149425,339,9,50.847927,52.635933
33,17,Opponent17,0.171018,362,9,50.270146,42.886994
69,35,Opponent17,0.209224,240,9,44.786671,54.019171
35,18,Opponent18,0.173472,302,7,46.391850,47.857593
67,34,Opponent18,0.135675,256,7,49.628512,54.414019
39,20,Opponent19,0.156238,230,7,51.250019,49.445308
47,24,Opponent19,0.159993,186,7,44.231576,45.023978
3,2,Opponent2,0.196135,416,9,51.924433,50.500290
63,32,Opponent2,0.117319,877,10,48.680790,48.923759
5,3,Opponent3,0.166204,471,9,50.359856,51.301667
37,19,Opponent3,0.163765,498,8,52.854911,53.821654
7,4,Opponent4,0.128294,345,9,53.742768,43.213589
45,23,Opponent4,0.155690,473,9,48.579560,51.548916
9,5,Opponent5,0.138819,373,8,55.291332,46.223545
43,22,Opponent5,0.147809,476,8,51.704669,47.061751
11,6,Opponent6,0.140769,294,8,51.848631,47.471446
41,21,Opponent6,0.107808,204,9,50.533589,45.582867
13,7,Opponent7,0.252787,179,8,45.476975,46.471713
57,29,Opponent7,0.176476,225,7,51.581861,46.732651
15,8,Opponent8,0.213900,277,7,46.803722,48.411707
59,30,Opponent8,0.168059,172,7,46.154208,47.133174
17,9,Opponent9,0.122462,501,8,47.771329,48.264077
51,26,Opponent9,0.164418,362,7,42.996269,44.319426

In [13]:
match31 = df[df['matchID']==31]
match6 = df[df['matchID']==6]
match9 = df[df['matchID']==9]

In [11]:
cent31 = cent[cent['matchID']==31]
cent6 = cent[cent['matchID']==6]
cent9 = cent[cent['matchID']==9]

In [9]:
pass31 = passes[passes['MatchID'] == 31]
pass6 = passes[passes['MatchID'] == 6]
pass9 = passes[passes['MatchID'] == 9]

In [38]:
match31

,matchID,teamID,avg_clustering,total_degree,clique_number,avg_position_x,avg_position_y
60,31,Huskies,0.182739,329,9,47.926444,49.534544
61,31,Opponent1,0.195581,215,7,48.001386,46.351348

In [35]:
pass31

    MatchID  total  success      rate  Ototal  Osuccess     Orate
30       31    430      329  0.765116     301       215  0.714286

In [40]:
cent31 = cent31.sort_values('centrality', ascending=False)
cent31

,matchID,teamID,PlayerID,clustering,out_degree,centrality,avg_position_x,avg_position_y
426,31,Huskies,Huskies_M1,0.193291,11,2.681509,50.311111,47.311111
422,31,Huskies,Huskies_F2,0.233121,10,2.615987,53.137255,53.901961
419,31,Huskies,Huskies_D4,0.201110,11,2.542097,48.731707,13.512195
420,31,Huskies,Huskies_D8,0.157798,10,2.458151,48.185185,82.370370
417,31,Huskies,Huskies_D1,0.230808,11,2.366026,36.375000,40.250000
418,31,Huskies,Huskies_D3,0.216284,10,2.326885,34.975610,69.756098
424,31,Huskies,Huskies_F6,0.175804,9,2.062052,66.304348,80.565217
427,31,Huskies,Huskies_M12,0.155043,7,1.934684,62.583333,15.416667
425,31,Huskies,Huskies_G1,0.181509,8,1.855403,11.266667,46.800000
421,31,Huskies,Huskies_F1,0.171797,5,1.800693,57.600000,43.800000
423,31,Huskies,Huskies_F5,0.137921,6,1.774928,68.800000,51.800000
428,31,Huskies,Huskies_M4,0.208853,4,1.645983,50.200000,46.000000
429,31,Huskies,Huskies_M3,0.196941,1,1.187516,43.000000,25.500000
430,31,Huskies,Huskies_D6,0.098072,2,0.817712,39.500000,76.500000